version: "3"
services:
  facebook-api:
    image: "node:8-alpine"
    command: yarn run dev
    environment:
      DATABASE_URL: mongodb://mongodb/facebook-api
    volumes:
      - .:/src
    working_dir: /src
    links:
      - mongodb
    ports:
      - 3000:3000

  mongodb:
    image: mongo
